---
- name: Download erigon
  ansible.builtin.get_url:
    url: "https://github.com/ledgerwatch/erigon/releases/download/v{{- ethereum_erigon_version -}}/erigon_{{- ethereum_erigon_version -}}_linux_amd64.tar.gz"
    dest: &erigondest /tmp/erigon.tar.gz
    mode: '0600'

- name: Unpack erigon
  ansible.builtin.unarchive:
    src: *erigondest
    remote_src: true
    dest: /tmp

- name: Copy erigon binary
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/erigon"
    dest: /home/ethereum/ethereum/execution/
    owner: ethereum
    group: ethereum
    mode: '0755'

- name: Copy service files
  ansible.builtin.template:
    src: "lib/systemd/system/execution-erigon.service.j2"
    dest: "/lib/systemd/system/execution.service"
    owner: root
    group: root
    mode: '0644'

- name: Start execution
  ansible.builtin.systemd:
    name: execution
    state: started
    enabled: true
    daemon_reload: true
  when: not ansible_check_mode