---
- name: Install required software
  ansible.builtin.apt:
    pkg:
      - libsnappy-dev

- name: Download execution
  ansible.builtin.get_url:
    url: "https://nethdev.blob.core.windows.net/builds/nethermind-{{- ethereum_nethermind_version -}}-linux-x64.zip"
    dest: &nethdest /tmp/nethermind.tar.gz
    mode: '0600'

- name: Unpack execution
  ansible.builtin.unarchive:
    src: *nethdest
    remote_src: true
    dest: /home/ethereum/ethereum/execution


- name: Copy service files
  ansible.builtin.template:
    src: "lib/systemd/system/execution-nethermind.service.j2"
    dest: "/lib/systemd/system/execution.service"
    owner: root
    group: root
    mode: '0644'

- name: Start execution
  ansible.builtin.systemd:
    name: execution
    state: started
    enabled: true
    daemon_reload: true
  when: not ansible_check_mode