---
- name: Copy service files
  ansible.builtin.template:
    src: "{{- item -}}.j2"
    dest: "/{{- item -}}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - lib/systemd/system/consensus.service
    - lib/systemd/system/execution.service

- name: Start consensus
  ansible.builtin.systemd:
    name: consensus
    state: started
    enabled: true
    daemon_reload: true
  when: not ansible_check_mode

- name: Start execution
  ansible.builtin.systemd:
    name: execution
    state: started
    enabled: true
    daemon_reload: true
  when: not ansible_check_mode