extra_hosts:
# physical servers
  - ip: 192.168.1.38
    name: cracow32.local
  - ip: 10.8.0.38
    name: cracow32.vpn.vallheru.pl
  - ip: 10.8.0.38
    name: cracow32.vpn

  - ip: 192.168.1.40
    name: cracow16.local
  - ip: 10.8.0.40
    name: cracow16.vpn.vallheru.pl
  - ip: 10.8.0.40
    name: cracow16.vpn

  - ip: 192.168.1.41
    name: cracowrpi.local
  - ip: 10.8.0.41
    name: cracowrpi.vpn.vallheru.pl
  - ip: 10.8.0.41
    name: cracowrpi.vpn

  - ip: 192.168.1.79
    name: prodeskg11.local
  - ip: 10.8.0.79
    name: prodeskg11.vpn.vallheru.pl
  - ip: 10.8.0.79
    name: prodeskg11.vpn

  - ip: 192.168.1.78
    name: prodeskg10.local
  - ip: 10.8.0.78
    name: prodeskg10.vpn.vallheru.pl
  - ip: 10.8.0.78
    name: prodeskg10.vpn

  - ip: 192.168.1.75
    name: prodeskg2.local
  - ip: 10.8.0.75
    name: prodeskg2.vpn.vallheru.pl
  - ip: 10.8.0.75
    name: prodeskg2.vpn

## apps
  - ip: 192.168.1.200
    name: guacamole.local
  - ip: 10.8.0.200
    name: guacamole.vpn.vallheru.pl
  - ip: 10.8.0.200
    name: guacamole.vpn
  
  - ip: 192.168.1.201
    name: webapps.local
  - ip: 10.8.0.201
    name: webapps.vpn.vallheru.pl
  - ip: 10.8.0.201
    name: webapps.vpn

  - ip: 192.168.1.202
    name: vega.local
  - ip: 10.8.0.202
    name: vega.vpn.vallheru.pl
  - ip: 10.8.0.202
    name: vega.vpn
    
  - ip: 192.168.1.203
    name: sepolia-archival.local
  - ip: 10.8.0.203
    name: sepolia-archival.vpn.vallheru.pl
  - ip: 10.8.0.203
    name: sepolia-archival.vpn

  - ip: 192.168.1.204
    name: postgresql.local
  - ip: 10.8.0.204
    name: postgresql.vpn.vallheru.pl
  - ip: 10.8.0.204
    name: postgresql.vpn

  - ip: 192.168.1.205
    name: monitoring.local
  - ip: 10.8.0.205
    name: monitoring.vpn.vallheru.pl
  - ip: 10.8.0.205
    name: monitoring.vpn

extra_accounts:
  daniel:
    authorized_keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChCUeQhmZAUIuQbLAL98T9nreZIffvTQ7MbwgD3I2dWNTw3zlxEZFBiTBcK4C60AcuaRkQxiJTrKB/34JaTSFkNLh+qQUwgzKHVL5cEaIZ43X0diA+PFxwP05huhKAjnI4U9T2pub/JhjC677vHTFwHKOTEe37t3KXKvKUGbhz38CK7wPkiMWyDUmCfmMq7vHOoiIFfFAD33O4kDpdV3fGNx/y/1evSPSDojvVoMq+xFNmRLYmQQdfwWRJdGv1Sf6vA9kCu20995BzycJXDYf15uUsMxpsAohqs0eY6Q0su57eSEX3oInbtg6ChVmSV83rWlW4+h5LBt5I4UR8YVv8P/Vg9oRz6fqvcxkS5AE6hkVv+FCg69rCGLmODLr+U/S1RheOfN/HwxbGx+/eatlGjphi6mWcjRGHIBI37Tv0TeKXSqCi/1419FNZozTjlj5YzdLmhOSldQWXIqtPSqp7mUnWZF8lMY/VPyAeKR5um7KC7pJfrNVstUmDrxIHIyU= daniel@Daniels-MacBook-Pro.local
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGOXbUTi/Y49LMKUJBxOHHnQFlCSppH7bKlgz3GEatZj danielhornik@Daniels-MBP.net
  