extra_hosts: []

common_with_qemu: false

extra_accounts:
  daniel:
    authorized_keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChCUeQhmZAUIuQbLAL98T9nreZIffvTQ7MbwgD3I2dWNTw3zlxEZFBiTBcK4C60AcuaRkQxiJTrKB/34JaTSFkNLh+qQUwgzKHVL5cEaIZ43X0diA+PFxwP05huhKAjnI4U9T2pub/JhjC677vHTFwHKOTEe37t3KXKvKUGbhz38CK7wPkiMWyDUmCfmMq7vHOoiIFfFAD33O4kDpdV3fGNx/y/1evSPSDojvVoMq+xFNmRLYmQQdfwWRJdGv1Sf6vA9kCu20995BzycJXDYf15uUsMxpsAohqs0eY6Q0su57eSEX3oInbtg6ChVmSV83rWlW4+h5LBt5I4UR8YVv8P/Vg9oRz6fqvcxkS5AE6hkVv+FCg69rCGLmODLr+U/S1RheOfN/HwxbGx+/eatlGjphi6mWcjRGHIBI37Tv0TeKXSqCi/1419FNZozTjlj5YzdLmhOSldQWXIqtPSqp7mUnWZF8lMY/VPyAeKR5um7KC7pJfrNVstUmDrxIHIyU= daniel@Daniels-MacBook-Pro.local
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGOXbUTi/Y49LMKUJBxOHHnQFlCSppH7bKlgz3GEatZj danielhornik@Daniels-MBP.net
  