---
- name: Create required directory structure
  ansible.builtin.file:
    path: "{{- item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  with_items:
    - "/var/lib"
    - "/var/lib/node_exporter"
    - "/var/lib/node_exporter/textfile_collector"