
---
- name: Download nginxlog-exporter
  ansible.builtin.get_url:
    url: "https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v{{- grafana_agent_nginxlog_exporter_version -}}/prometheus-nginxlog-exporter_{{- grafana_agent_nginxlog_exporter_version -}}_linux_amd64.tar.gz"
    dest: &nginxlog_exporterdesc /tmp/nginxlog_exporter.tar.gz
    mode: '0600'

- name: Unpack nginxlog-exporter
  ansible.builtin.unarchive:
    src: *nginxlog_exporterdesc
    remote_src: true
    dest: /tmp

- name: Copy nginxlog-exporter binary
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/prometheus-nginxlog-exporter"
    dest: /usr/local/bin/prometheus-nginxlog-exporter
    owner: root
    group: root
    mode: '0755'

- name: Create config dir
  ansible.builtin.file:
    path: /etc/nginxlog-exporter
    state: directory
    owner: root
    group: root

- name: Render config template
  ansible.builtin.template:
    src: "etc/nginxlog-exporter/config.hcl.j2"
    dest: "/etc/nginxlog-exporter/config.hcl"
    owner: root
    group: root
    mode: '0644'

- name: Copy service files
  ansible.builtin.template:
    src: "lib/systemd/system/nginxlog-exporter.j2"
    dest: "/lib/systemd/system/nginxlog-exporter.service"
    owner: root
    group: root
    mode: '0644'

- name: Start execution
  ansible.builtin.systemd:
    name: nginxlog-exporter
    state: started
    enabled: true
    daemon_reload: true
  when: not ansible_check_mode