- name: Install prerequisites software
  ansible.builtin.apt:
    pkg:
      - gnupg
      - gnupg2
      - gnupg1
      - libxml2
      - ffmpeg
      - unzip
      - libreoffice
      - libreoffice-common

- name: Check that the /var/www/nextcloud exists
  ansible.builtin.stat:
    path: /var/www/nextcloud
  register: stat_result

- name: Install nextcloud
  when: not stat_result.stat.exists
  block:
    - name: Download nextcloud
      ansible.builtin.get_url:
        url: https://download.nextcloud.com/server/releases/nextcloud-28.0.0.zip
        dest: /tmp/nextcloud.zip
        mode: '0664'
        owner: root
        group: root

    - name: Create home for nextcloud
      ansible.builtin.file:
        path: /var/www/nextcloud
        state: directory
        owner: www-data
        group: www-data
        mode: 0700

    - name: Extract /tmp/nextcloud.zip into /var/www/nextcloud
      ansible.builtin.unarchive:
        src: /tmp/nextcloud.zip
        remote_src: true
        dest: /var/www
        owner: www-data
        group: www-data


    - name: nginx config
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0600
      with_items:
        - src: 'etc/nginx/sites-enabled/01-nextcloud.local.mainnet.community.conf'
          dest: '/etc/nginx/sites-enabled/01-nextcloud.local.mainnet.community.conf'


    - name: Restart nginx
      ansible.builtin.service:
        state: restarted
        name: nginx
        enabled: true