---
- name: Check that the /bin/dasel exists
  ansible.builtin.stat:
    path: /bin/dasel
  register: dasel_result

- name: Install gzip
  when: not dasel_result.stat.exists
  block:
    - name: Download dasel
      ansible.builtin.get_url:
        url: https://github.com/TomWright/dasel/releases/download/v2.5.0/dasel_linux_amd64.gz
        dest: /tmp/dasel.gz
        mode: '0664'
        owner: root
        group: root
        force: true

    - name: Extract dasel binaries
      ansible.builtin.shell: gzip -d /tmp/dasel.gz
      args:
        creates: /tmp/dasel

    - name: Move dasel to path
      ansible.builtin.shell: mv /tmp/dasel /bin/dasel
      args:
        creates: /bin/dasel

    - name: Give execution permissions for dasel
      ansible.builtin.file:
        path: /bin/dasel
        owner: root
        group: root
        mode: '077'
