---
- name: Install qemu-guest-agent
  when: common_with_qemu 
  block:
    - name: Install required software
      ansible.builtin.apt:
        pkg:
          - qemu-guest-agent

    - name: Start qemu-agent
      ansible.builtin.systemd:
        name: qemu-guest-agent
        state: started
        enabled: true
        daemon_reload: true