- name: Install required software
  ansible.builtin.apt:
    pkg:
      - sudo
      - git
      - wget
      - curl
      - vim
      - gnupg
      - gnupg2
      - gnupg1
      - acl
      - nfs-common
      - unzip
      - gzip
      - qemu-guest-agent

- name: Ensure users can access sudo w/o pass
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "[%]?sudo[\\s]+ALL"
    line: "%sudo   ALL=(ALL:ALL) NOPASSWD:ALL"